drop table if exists accounts CASCADE 
drop table if exists banks CASCADE 
create table accounts (id bigint generated by default as identity, balance numeric(19,2), person_name varchar(255), primary key (id))
create table banks (id bigint generated by default as identity, bank_name varchar(255), total_transfers integer, primary key (id))
INSERT INTO accounts (person_name, balance) VALUES ('Andrés', 1000), ('John', 2000)
INSERT INTO banks (bank_name, total_transfers) VALUES ('BBVA', 0)